name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.x
      - name: Build
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install . --deps-only
          opam exec -- make
